spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database?serverTimezone=Asia/Seoul
    username: sa
    password:
  config:
    import: classpath:private/private.yml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  profiles:
    active: dev

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    enabled: true

odsay:
  url: https://api.odsay.com/v1/api/searchPubTransPathT

---

spring:
  config:
    activate:
      on-profile: local

log:
  file:
    path: ./ody-dev-logs

---

spring:
  config:
    activate:
      on-profile: dev

log:
  file:
    path: /ody-dev-logs

---

spring:
  config:
    activate:
      on-profile: prod

log:
  file:
    path: /ody-prod-logs
